export const projects = [
  {
    id: 1,
    img: require('./../assets/img/project-image.jpg'),
    title: 'Me Project',
    description: "Here, you'll see the project from this site, I've thinked add a blog as well, you'll see it soon.",
    tags: ['Javascript', 'React JS', 'Next JS'],
    urlWeb: '',
    urlHosted: 'https://github.com/Llerena97/me-project',
  },
  {
    id: 2,
    img: require('./../assets/img/project-image.jpg'),
    title: 'Task Frontend',
    description: "This app works to manage project tasks. Currently, I'm working in the backend integration.",
    tags: ['Javascript', 'React JS', 'React Context'],
    urlWeb: 'https://tasks-frontend.vercel.app/',
    urlHosted: 'https://github.com/Llerena97/tasks-frontend/',
  },
  {
    id: 3,
    img: require('./../assets/img/rails-img.jpg'),
    title: 'Rails Shop',
    description: "This project is a manual emulation of a shopping cart made in ruby ​​on rails, this project is connected to AWS S3 for file management.",
    tags: ['Ruby', 'Ruby on Rails', 'Amazon S3'],
    urlWeb: 'https://ra1ls-shop.herokuapp.com/',
    urlHosted: 'https://github.com/Llerena97/rails-shop',
  },
  {
    id: 4,
    img: require('./../assets/img/rails-img.jpg'),
    title: 'Contacts API',
    description: "I made this API when I participated in a Hackathon organized by Koombea, in the github link you'll see their specifications.",
    tags: ['Ruby', 'Ruby on Rails'],
    urlWeb: '',
    urlHosted: 'https://github.com/Llerena97/Contacts',
  },
  {
    id: 5,
    img: require('./../assets/img/bootstrap-img.png'),
    title: 'Ferreagro Project',
    description: "This was one of my first projects for a client in the city, where I was able to take my first steps in software web development and I'm close to negotiating improvements.",
    tags: ['Bootstrap'],
    urlWeb: 'http://ferreagrodelcaribe.co/',
    urlHosted: '',
  }
]